#!/bin/sh
set -eu

# Manual test-oracle helper. DEVELOPER TOOL ONLY.
#
# This is the one place in the repository that runs an external `openscad`
# binary, and it does so purely as a reference oracle: it renders *our own*
# `.scad` sources (the Appa fixtures) and diffs the result against the
# checked-in STL goldens. Comparing output against a reference implementation
# is not deriving from it — no upstream code enters this project, and the
# sibling `openscad/` checkout is never built, linked, or shipped.
#
# It is NOT a cargo target (cargo only builds `.rs` files under `tests/`), it
# is excluded from the container image by `web/.dockerignore`, and it never
# runs during `cargo test` or in CI. The production server never invokes
# OpenSCAD.
#
# With no argument (or `check`), render references into a temporary directory
# and compare them byte-for-byte with the checked-in fixtures. `regenerate`
# replaces fixture STLs only after an explicit confirmation environment flag:
#
#   ALLOW_ORACLE_REGENERATION=1 tests/oracle.sh regenerate

mode=${1:-check}
case "$mode" in
  check|regenerate) ;;
  *) echo "usage: $0 [check|regenerate]" >&2; exit 2 ;;
esac

command -v openscad >/dev/null 2>&1 || {
  echo "openscad is required only for this manual oracle operation" >&2
  exit 1
}

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# Every fixture directory carrying a cases.tsv. `openappa` is the corpus the
# kernel passes; `hard-geometry` is the one it does not. Both are rendered by
# the same oracle so a golden can never be regenerated by a different route
# from the one that produced its neighbours.
fixture_dirs="openappa hard-geometry"
temporary_dir=$(mktemp -d "${TMPDIR:-/tmp}/reopenscad-oracles.XXXXXX")
trap 'rm -rf "$temporary_dir"' EXIT HUP INT TERM

status=0
for fixture_name in $fixture_dirs; do
fixture_dir="$script_dir/fixtures/$fixture_name"
[ -f "$fixture_dir/cases.tsv" ] || { echo "no manifest in $fixture_name, skipping" >&2; continue; }
echo "== $fixture_name ==" >&2

manifest="$temporary_dir/cases.tsv"
# Accept both literal tabs and the visible `\t` delimiters used by the
# committed manifest, and re-delimit onto `|`.
#
# Not cosmetic: a tab is IFS *whitespace*, and the shell folds a run of IFS
# whitespace into a single delimiter. Any case with an empty `definitions`
# column therefore lost a field and shifted the rest along, so `read` bound
# the reference STL to `source` and the oracle was handed a binary mesh to
# parse -- which is what "syntax error in openappa-fast-printing.scad" always
# was. `|` is not IFS whitespace, so empty fields survive it. It cannot occur
# in a case id, a filename or a `-D` assignment, and the guard below refuses
# to run at all if one ever does.
sep='|'
grep -q '|' "$fixture_dir/cases.tsv" && {
  echo "$fixture_name/cases.tsv contains '|', which this script uses as its delimiter" >&2
  exit 2
}
awk -v sep="$sep" '{ gsub(/\\t/, sep); gsub(/\t/, sep); print }' "$fixture_dir/cases.tsv" > "$manifest"

while IFS="$sep" read -r case_id source definitions reference; do
  case "$case_id" in ''|'#'*) continue ;; esac
  output="$temporary_dir/$reference"
  set -- openscad --export-format binstl -o "$output"
  old_ifs=$IFS
  IFS=';'
  for definition in $definitions; do
    [ -n "$definition" ] && set -- "$@" -D "$definition"
  done
  IFS=$old_ifs
  set -- "$@" "$fixture_dir/$source"
  echo "rendering $case_id" >&2
  # A case the oracle itself cannot render is a failure to report, not a
  # reason to abandon the other fixture directories: the OpenAPPA sources
  # stopped parsing under a newer OpenSCAD, and under `set -e` that silently
  # meant the hard-geometry goldens were never checked at all.
  if ! "$@"; then
    echo "oracle failed to render: $case_id" >&2
    status=1
  fi
done < "$manifest"

if [ "$mode" = regenerate ]; then
  [ "${ALLOW_ORACLE_REGENERATION:-}" = 1 ] || {
    echo "set ALLOW_ORACLE_REGENERATION=1 to replace checked-in references" >&2
    exit 2
  }
  while IFS="$sep" read -r case_id _source _definitions reference; do
    case "$case_id" in ''|'#'*) continue ;; esac
    cp "$temporary_dir/$reference" "$fixture_dir/$reference"
  done < "$manifest"
  echo "regenerated $fixture_name STL fixtures" >&2
  continue
fi

while IFS="$sep" read -r case_id _source _definitions reference; do
  case "$case_id" in ''|'#'*) continue ;; esac
  if cmp -s "$temporary_dir/$reference" "$fixture_dir/$reference"; then
    echo "ok: $case_id"
  else
    echo "different: $case_id (STL serialization or geometry changed)" >&2
    status=1
  fi
done < "$manifest"
done
exit "$status"
